# Generated by Django 5.2 on 2026-04-09 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_update', 'Application Status Updated'), ('new_job_match', 'New Job Matching Your Alert'), ('job_alert', 'Job Alert'), ('system', 'System Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('remote_type', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=20, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('frequency', models.CharField(choices=[('instant', 'Instant (on match)'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
