# Generated by Django 5.2 on 2026-05-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='verification/evidence/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
