# Generated by Django 6.0.4 on 2026-04-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('remotive_rss', 'Remotive RSS'), ('weworkremotely_rss', 'WeWorkRemotely RSS'), ('adzuna_api', 'Adzuna API'), ('jsearch_api', 'JSearch API'), ('manual', 'Manual Import')], max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('jobs_fetched', models.PositiveIntegerField(default=0)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('jobs_skipped', models.PositiveIntegerField(default=0)),
                ('jobs_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
