# Generated by Django 5.2 on 2026-04-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_url', models.URLField(blank=True, default='')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applicant_name', models.CharField(blank=True, default='', max_length=200)),
                ('applicant_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('offer_made', 'Offer Made'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=30)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True, default='')),
                ('employer_notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
