# Generated by Django 5.2 on 2026-04-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='NGN', max_length=3)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('paystack_id', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('paystack_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('featured', 'Featured'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveSmallIntegerField(default=30)),
                ('max_job_posts', models.PositiveSmallIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['price_ngn'],
            },
        ),
    ]
