# Generated by Django 5.2 on 2026-04-09 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpayment',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobpayment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentplan'),
        ),
        migrations.AddIndex(
            model_name='jobpayment',
            index=models.Index(fields=['reference'], name='payments_jo_referen_994bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpayment',
            index=models.Index(fields=['status'], name='payments_jo_status_da3a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpayment',
            index=models.Index(fields=['employer'], name='payments_jo_employe_e02224_idx'),
        ),
    ]
