# Generated by Django 5.2 on 2026-04-09 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, default='Remote', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=50)),
                ('remote_type', models.CharField(choices=[('fully_remote', 'Fully Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site')], default='fully_remote', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('executive', 'Executive')], max_length=20, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('application_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_aggregated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
